import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ChakraBox from "@/providers/ChakraProvider";
// import { RtlProvider } from '@/components/rtl-provider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={inter.className}>
        <ChakraBox>
            {children}
        </ChakraBox>
      </body>
    </html>
  );
}
