import type { Metadata } from "next";
import "./globals.css";
import ChakraBox from "@/providers/ChakraProvider";
import localFont from 'next/font/local'
import { Box, Button, HStack, IconButton, Spacer, Flex, Link } from '@chakra-ui/react';


const gandom = localFont({ src: '../../public/fonts/Gandom.ttf' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={gandom.className}>
        <ChakraBox>
          <Box className="">
            {children}
          </Box>
        </ChakraBox>
      </body>
    </html>
  );
}
